# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbce7e42e8fdd2c46f7ee755f4ae9822138407328426d2b95203c4efb30bf9eb1ac37a3938b138a60662a4db3c2298912802eed598a0b9e38d2bcff2f547703b

test:
  secret_key_base: 0f48073d9adb257d58c8b94189659db66ccd8afc6d5d12bf568e938d65b703791b24feb22b5aed350afe0267ec73f8d40dfb3ceb823c6417dc9b2af9fdc6b342

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
